name = "world-album-discovery"
compatibility_date = "2026-05-03"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "world-album-db"
database_id = "263cea64-a8a3-411c-88dc-7f8abf7e4e6a"

[[kv_namespaces]]
binding = "CACHE"
id = "c061e94b0adf4f089aabf14e9227e5b9"
