name = "world-album-discovery"
compatibility_date = "2026-05-03"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "world-album-db"
database_id = "6c292c43-78d8-4dd2-af38-2d0ed2ccd91d"

[[kv_namespaces]]
binding = "CACHE"
id = "c061e94b0adf4f089aabf14e9227e5b9"
